RPSLS_GAME::Program
static void RPSLS_GAME.Program.Main(string[] args)
The Main.
args The argsstring[].
References RPSLS_GAME.Program.GameInitialize.
static void RPSLS_GAME.Program.GameInitialize()
The GameInitialize.
References RPSLS_GAME.Program.UserAction.
Referenced by RPSLS_GAME.Program.ChoosedOptionValidation, RPSLS_GAME.Program.Main.
static void RPSLS_GAME.Program.UserAction()
The UserAction.
References RPSLS_GAME.Program.ChoosedOptionValidation, RPSLS_GAME.Program.PressedKeyValidation, RPSLS_GAME.Program.StoreUserInput, RPSLS_GAME.Program.WaitForUser.
Referenced by RPSLS_GAME.Program.GameFinalize, RPSLS_GAME.Program.GameInitialize, RPSLS_GAME.Program.GameRulesHelper.
static void RPSLS_GAME.Program.ChoosedOptionValidation(char UserPressedKey)
The ChoosedOptionValidation.
UserPressedKey The UserPressedKeychar.
References RPSLS_GAME.Program.GameInitialize, RPSLS_GAME.Program.GameRulesHelper, RPSLS_GAME.Program.GameTable.
Referenced by RPSLS_GAME.Program.UserAction.
static char RPSLS_GAME.Program.PressedKeyValidation(char UserPressedKey)
The PressedKeyValidation.
UserPressedKey The UserPressedKeychar. The char.
References RPSLS_GAME.Program.StoreUserInput, RPSLS_GAME.Program.WaitForUser.
Referenced by RPSLS_GAME.Program.UserAction.
static char RPSLS_GAME.Program.StoreUserInput()
The StoreUserInput.
The char.
Referenced by RPSLS_GAME.Program.CheckPressedKey, RPSLS_GAME.Program.ChoosedKeyValidation, RPSLS_GAME.Program.GameLogic, RPSLS_GAME.Program.PressedKeyValidation, RPSLS_GAME.Program.UserAction.
static void RPSLS_GAME.Program.WaitForUser()
The WaitForUser.
Referenced by RPSLS_GAME.Program.ChoosedKeyValidation, RPSLS_GAME.Program.PressedKeyValidation, RPSLS_GAME.Program.UserAction.
static void RPSLS_GAME.Program.GameRulesHelper()
The GameRulesHelper.
References RPSLS_GAME.Program.HelperUI, RPSLS_GAME.Program.UserAction.
Referenced by RPSLS_GAME.Program.ChoosedOptionValidation.
static void RPSLS_GAME.Program.HelperUI()
The HelperUI.
Referenced by RPSLS_GAME.Program.GameRulesHelper.
static void RPSLS_GAME.Program.GameTable()
The GameTable.
References RPSLS_GAME.Program.GameFinalize, RPSLS_GAME.Program.GameLogic, RPSLS_GAME.Program.GameStart, RPSLS_GAME.Program.SaveGameData.
Referenced by RPSLS_GAME.Program.ChoosedOptionValidation.
static void RPSLS_GAME.Program.GameLogic(out char UserPressedKey, out char MachinePressedKey)
The GameLogic.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar.
References RPSLS_GAME.Program.CheckChoosedOption, RPSLS_GAME.Program.ChoosedKeyValidation, RPSLS_GAME.Program.MachineChoose, RPSLS_GAME.Program.StoreUserInput.
Referenced by RPSLS_GAME.Program.GameTable.
static char RPSLS_GAME.Program.ChoosedKeyValidation(char UserPressedKey)
The ChoosedKeyValidation.
UserPressedKey The UserPressedKeychar. The char.
References RPSLS_GAME.Program.StoreUserInput, RPSLS_GAME.Program.WaitForUser.
Referenced by RPSLS_GAME.Program.GameLogic.
static void RPSLS_GAME.Program.GameStart()
The GameStart.
Referenced by RPSLS_GAME.Program.GameTable.
static void RPSLS_GAME.Program.GameFinalize()
The GameFinalize.
References RPSLS_GAME.Program.UserAction.
Referenced by RPSLS_GAME.Program.GameTable.
static void RPSLS_GAME.Program.StoreTheResult(char UserPressedKey, char MachinePressedKey)
The StoreTheResult.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar.
References RPSLS_GAME.Program.DefineMachineChoosedOption, RPSLS_GAME.Program.DefineUserChoosedOption.
Referenced by RPSLS_GAME.Program.SaveGameData.
static string RPSLS_GAME.Program.DefineMachineChoosedOption(char MachinePressedKey, string Machinechoosedoption)
The DefineMachineChoosedOption.
MachinePressedKey The MachinePressedKeychar. Machinechoosedoption The Machinechoosedoptionstring. The string.
Referenced by RPSLS_GAME.Program.StoreTheResult.
static string RPSLS_GAME.Program.DefineUserChoosedOption(char UserPressedKey, string Userchoosedoption)
The DefineUserChoosedOption.
UserPressedKey The UserPressedKeychar. Userchoosedoption The Userchoosedoptionstring. The string.
Referenced by RPSLS_GAME.Program.StoreTheResult.
static void RPSLS_GAME.Program.CheckChoosedOption(ref char UserPressedKey, ref char MachinePressedKey)
The CheckChoosedOption.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar.
References RPSLS_GAME.Program.CheckPressedKey, RPSLS_GAME.Program.PrintResult.
Referenced by RPSLS_GAME.Program.GameLogic.
static void RPSLS_GAME.Program.CheckPressedKey(ref char UserPressedKey, ref char MachinePressedKey, out int UserPoint, out int MachinePoint)
The CheckPressedKey.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar. UserPoint The UserPointint. MachinePoint The MachinePointint.
References RPSLS_GAME.Program.MachineChoose, RPSLS_GAME.Program.RulesCheck, RPSLS_GAME.Program.StoreUserInput.
Referenced by RPSLS_GAME.Program.CheckChoosedOption.
static void RPSLS_GAME.Program.RulesCheck(char UserPressedKey, char MachinePressedKey, ref int UserPoint, ref int MachinePoint)
The RulesCheck.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar. UserPoint The UserPointint. MachinePoint The MachinePointint.
Referenced by RPSLS_GAME.Program.CheckPressedKey.
static void RPSLS_GAME.Program.PrintResult(int UserPoint, int MachinePoint)
The PrintResult.
UserPoint The UserPointint. MachinePoint The MachinePointint.
Referenced by RPSLS_GAME.Program.CheckChoosedOption.
static char RPSLS_GAME.Program.MachineChoose()
The MachineChoose.
The char.
Referenced by RPSLS_GAME.Program.CheckPressedKey, RPSLS_GAME.Program.GameLogic.
static void RPSLS_GAME.Program.SaveGameData(char UserPressedKey, char MachinePressedKey)
The SaveGameData.
UserPressedKey The UserPressedKeychar. MachinePressedKey The MachinePressedKeychar.
References RPSLS_GAME.Program.StoreTheResult.
Referenced by RPSLS_GAME.Program.GameTable.